<a href="https://colab.research.google.com/github/naikshrey2308/ML_Labs/blob/main/ML_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Probablistic Models in Machine Learning

1. Naive Bayes Classifier

In [ ]:
# Import the necessary libraries

import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB, MultinomialNB, CategoricalNB

In [ ]:
# Creating the dataset

weather = np.array(['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy'])

temp = np.array(['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild'])

play = np.array(['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No'])

In [ ]:
# Prime the data by filtering it

le = LabelEncoder()
weather_encoded = le.fit_transform(weather)
temp_encoded = le.fit_transform(temp)
label = le.fit_transform(play)
weather_encoded, temp_encoded, label

(array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1]),
 array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2]),
 array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0]))

In [ ]:
# Combine the features to feed them into the model

features = tuple(zip(weather_encoded, temp_encoded))
features

((2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2))

In [ ]:
# Create a classifier

# model = MultinomialNB()
# model = GaussianNB()
model = CategoricalNB()
model.fit(features, label)

# weather_input = int(input())
# temp_input = int(input())

predictions = []
for i in range(3):
    for j in range(3):
        predictions[:0] = model.predict([[i, j]])

predictions

[0, 0, 1, 1, 1, 1, 1, 1, 1]

Exercise Questions:

In [ ]:
# 1
# will you play if temp = hot and weather = overcast?
# will you play if temp = mild and weather = sunny?
model.predict([[0, 1], [2, 2]])

array([1, 0])

2. Gaussian Classifier Iris Dataset

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()

In [ ]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
iris.target_names 

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
newdata = iris.data[50:]
newtargets = iris.target[50:]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(newdata, newtargets, test_size=0.25, random_state=5)

gnb = GaussianNB()
gnb.fit(X_train, y_train)
predictions = gnb.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [ ]:
score = accuracy_score(y_test, predictions)
score

0.88

In [ ]:
confusion_matrix(y_test, predictions)

array([[15,  1],
       [ 2,  7]])

In [ ]:
score = precision_score(y_test, predictions)
score

0.8823529411764706

In [ ]:
score = recall_score(y_test, predictions)
score

0.9375

3. Gaussian Classifier Iris Dataset (3 Classes)

Task #1

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = pd.read_csv("drive/MyDrive/Dataset2.csv")
data

Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N

In [ ]:
le = LabelEncoder()

In [ ]:
for i in data:
    data[i] = le.fit_transform(data[i])

In [ ]:
features = data.iloc[:, :-1]
labels = data.iloc[:, -1:]

In [ ]:
features

Outlook  Temp  Wind  Humidity
0         1     1     0         2
1         1     1     1         0
2         0     1     0         2
3         2     2     0         2
4         2     2     0         2
5         2     2     1         1
6         0     0     1         2
7         1     0     0         2
8         1     0     0         1
9         2     2     0         0
10        1     2     1         0
11        0     2     1         1
12        0     1     0         2
13        2     2     1         2

In [ ]:
labels

Class
0       0
1       0
2       1
3       0
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.1, random_state=1)

In [ ]:
X_train.shape, X_test.shape

((12, 4), (2, 4))

In [ ]:
gnb = GaussianNB()
gnb.fit(X_train, y_train.values.ravel())
predictions = gnb.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [ ]:
score = accuracy_score(y_test, predictions)
score

0.5

In [ ]:
score = precision_score(y_test, predictions)
score

0.5

In [ ]:
score = recall_score(y_test, predictions)
score

1.0

In [ ]:
cfm = confusion_matrix(y_test, predictions)
cfm

array([[0, 1],
       [0, 1]])

Exercise Questions

In [ ]:
# 3.1
# outlook = rainy, temp = mild, humidity = normal, wind = false
# outlook = sunny, temp = cool, humidity = high, wind = true
print(gnb.predict([[1, 2, 2, 0], [2, 0, 0, 1]]))
# 3.2 (3)
print(gnb.predict_proba([[1, 2, 2, 0], [2, 0, 0, 1]]))

[0 1]
[[0.53514985 0.46485015]
 [0.02810552 0.97189448]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


Task #2

In [ ]:
digits = datasets.load_digits()

In [ ]:
features = np.array(digits.feature_names)
features

array(['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4',
       'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1',
       'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6',
       'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3',
       'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0',
       'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5',
       'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2',
       'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7',
       'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4',
       'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1',
       'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6',
       'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3',
       'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7'], dtype='<U9')

In [ ]:
labels = np.array(digits.target_names)
labels

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [ ]:
# therefore, 1797 are the number of data entries and 64 are the features
digits.target.shape, digits.data.shape

((1797,), (1797, 64))

In [ ]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder()
# features_encoded = ohe.fit_transform(features.reshape(-1,1)).toarray()
# print(features_encoded.shape)

In [ ]:
labels_encoded = ohe.fit_transform(digits.target.reshape(-1,1)).toarray()
labels_encoded

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.35)

In [ ]:
gnb.fit(X_train, y_train)
predictions = gnb.predict(X_test)
predictions

array([8, 4, 8, 6, 5, 3, 8, 5, 6, 0, 7, 7, 7, 1, 8, 5, 6, 5, 5, 4, 8, 1,
       6, 2, 8, 1, 1, 7, 9, 4, 3, 4, 8, 8, 5, 5, 0, 8, 6, 4, 4, 1, 4, 1,
       7, 7, 3, 8, 4, 2, 1, 6, 9, 8, 7, 5, 3, 4, 2, 1, 9, 0, 4, 0, 6, 5,
       3, 2, 6, 8, 7, 8, 6, 6, 4, 4, 6, 8, 4, 2, 1, 6, 8, 8, 3, 1, 0, 1,
       7, 3, 8, 6, 7, 4, 8, 3, 8, 5, 1, 5, 1, 8, 7, 7, 8, 0, 1, 8, 1, 1,
       3, 2, 6, 9, 7, 6, 1, 6, 2, 8, 4, 9, 6, 0, 8, 6, 4, 7, 3, 1, 0, 5,
       8, 5, 7, 6, 4, 0, 1, 6, 8, 1, 8, 7, 1, 9, 8, 1, 7, 3, 3, 5, 5, 3,
       1, 7, 5, 3, 6, 8, 8, 4, 1, 3, 0, 0, 6, 9, 2, 2, 1, 2, 4, 7, 3, 4,
       4, 2, 0, 6, 1, 5, 6, 3, 1, 1, 3, 2, 6, 1, 4, 9, 9, 3, 6, 5, 5, 0,
       5, 7, 4, 1, 2, 9, 0, 0, 8, 0, 3, 5, 3, 9, 6, 8, 8, 5, 7, 4, 1, 6,
       5, 8, 0, 7, 8, 1, 1, 0, 8, 2, 6, 1, 0, 7, 6, 4, 8, 0, 2, 9, 6, 2,
       1, 1, 7, 0, 9, 4, 9, 2, 7, 3, 0, 4, 2, 1, 4, 7, 7, 4, 2, 3, 5, 8,
       8, 0, 7, 8, 6, 7, 1, 4, 1, 4, 6, 7, 1, 3, 6, 4, 7, 5, 5, 6, 6, 2,
       7, 9, 2, 2, 8, 1, 4, 6, 9, 3, 2, 1, 8, 5, 3,

In [ ]:
precision_score(y_test, predictions, average="micro")

0.8267090620031796

In [ ]:
accuracy_score(y_test, predictions)

0.8267090620031796

In [ ]:
recall_score(y_test, predictions, average="micro")

0.8267090620031796